steps:
  # 1. Instalar dependencias (incluyendo PyYAML y requests si no vienen)
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
  
  # 2. Ejecutar el build de MkDocs (donde está el exploit en site_name)
  - name: 'python'
    entrypoint: 'python3'
    args: ['-m', 'mkdocs', 'build', '--config-file', 'mkdocs.yml']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '600s' # Tiempo suficiente para que el script se ejecute
